##########################################
# Site Settings

baseURL = "https://www.hegu.me/"
title = "何故小站"
languageCode = "en"
hasCJKLanguage = true
copyright = "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)"
theme = "meme"

[params.logo]
  url = "/images/my-logo.png"
  title = "何故小站"

googleAnalytics = 'G-4BMXNHL73E' 
newContentEditor = ""

defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false

titleCaseStyle = "none"
pluralizeListTitles = false
summaryLength = 42
enableEmoji = false
footnoteReturnLinkContents = "↩"
enableGitInfo = false
enableRobotsTXT = true

[permalinks]
    categories = "/categories/:slug/"
    tags = "/tags/:slug/"

[taxonomies]
    category = "categories"
    tag = "tags"

[frontmatter]
    lastmod = ["lastmod", ":git", ":fileModTime", ":default"]

[pagination]
    pagerSize = 5
    path = 'page'

[markup]
    defaultMarkdownHandler = "goldmark"

    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.parser]
            attribute = true
            autoHeadingID = true
            autoHeadingIDType = "github"
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = true
            xHTML = false

    [markup.highlight]
        codeFences = true
        lineNos = true
        lineNumbersInTable = true
        noClasses = false

[minify.tdewolff.html]
    keepWhitespace = false

[related]
    threshold = 80
    includeNewer = true
    toLower = true
    [[related.indices]]
        name = "categories"
        weight = 100
    [[related.indices]]
        name = "tags"
        weight = 95
    [[related.indices]]
        name = "date"
        weight = 10
        pattern = "2006"

[mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputFormats.SectionsAtom]
    mediaType = "application/atom+xml"
    baseName = "atom"

[outputFormats.SectionsRSS]
    mediaType = "application/rss+xml"
    baseName = "rss"

[outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "search"

[outputFormats.Algolia]
    mediaType = "application/json"
    baseName = "algolia"
    isPlainText = true
    notAlternative = true

[outputs]
    page = ["HTML"]
    home = ["HTML", "SectionsAtom", "SectionsRSS", "SearchIndex"]
    section = ["HTML"]
    taxonomy = ["HTML"]
    term = ["HTML"]

[services.rss]
    limit = 20

##########################################
# Menu Settings

[menu]
    [[menu.main]]
        pageref = "/"
        name = "首页"
        weight = 1
        pre = "internal"
        post = "home"
    [[menu.main]]
        pageref = "/posts/"
        name = "文章"
        weight = 2
        pre = "internal"
        post = "archive"
    [[menu.main]]
        pageref = "/categories/"
        name = "分类"
        weight = 3
        pre = "internal"
        post = "th"
    [[menu.main]]
        pageref = "/tags/"
        name = "标签"
        weight = 4
        pre = "internal"
        post = "tags"
    [[menu.main]]
        pageref = "/about/"
        name = "关于"
        weight = 5
        pre = "internal"
        post = "user-circle"
    [[menu.main]]
        weight = 6
        identifier = "theme-switcher"
    [[menu.main]]
        weight = 7
        identifier = "lang-switcher"
    [[menu.main]]
        weight = 8
        identifier = "search"
        post = "search"

##########################################
# Theme Settings

[params]
    # Header
    enableHeader = true
    enableHeaderAutoHide = false
    displayHeaderInHome = true
    headerBackground = "linear-gradient(90deg, #f795331a 0, #f370551a 15%, #ef4e7b1a 30%, #a166ab1a 44%, #5073b81a 58%, #1098ad1a 72%, #07b39b1a 86%, #6dba821a 100%)"
    headerLayout = "flex"
    enableNavToggle = true
    navHeight = "10em"

    # Brand Bar (inside header)
    siteBrandSVG = false
    siteLogo = "/images/my-logo.png"
    homeLogo = "/images/my-logo.png"
    siteName = "何故小站"
    siteBrandFontSize = 1
    siteBrandFontColor = "var(--color-contrast-high)"

    # 修复 listDateFormat 报错
    listDateFormat = "2006/01/02"

    # 修复 404 页面背景图变量
    fofPoster = "/images/404.png"

    # 修复 SCSS 报错
    listDatePosition = "left"
