##########################################

# Site Settings

baseURL = "https://www.hegu.me/"
title = "何故小站"
languageCode = "en"
hasCJKLanguage = true

# Copyright information (Markdown supported)

copyright = "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)"

# Google Analytics (已启用)

# Moved to [params] below

# hugo new automatically opened text editor
# Moved to [params] below

# i18n
# Moved to [params] below

# Title case style (https://gohugo.io/getting-started/configuration/#configure-title-case)
# Moved to [params] below

# Pluralize list titles
# Moved to [params] below

# The length of text in words to show in summary
# Moved to [params] below

# Enable Emoji emoticons support?
# Moved to [params] below

# Text to display for footnote return links
# Moved to [params] below

# Enable .GitInfo object for each page?
# Moved to [params] below

# Enable generation of robots.txt file?
# Moved to [params] below

# URL related
# Moved to [params] below

# URL structure

[permalinks]
categories = "/categories/:slug/"
tags = "/tags/:slug/"

# Taxonomies

[taxonomies]
category = "categories"
tag = "tags"

# Modified date

[frontmatter]
lastmod = ["lastmod", ":git", ":fileModTime", ":default"]

[pagination]
disableAliases = false

# Number of items per page in paginated lists (valid for the posts homepage layout in MemE)

pagerSize = 5
path = 'page'

# Markdown renderer

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = "github"
[markup.goldmark.parser.attribute]
block = true
title = true
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
[markup.highlight]
codeFences = true
guessSyntax = false
lineNos = true
lineNumbersInTable = true
noClasses = false
[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = true

# HTML minify

[minify.tdewolff.html]
keepWhitespace = false

# Related content

[related]
threshold = 80
includeNewer = true
toLower = true
[[related.indices]]
name = "categories"
weight = 100
[[related.indices]]
name = "tags"
weight = 95
[[related.indices]]
name = "date"
weight = 10
pattern = "2006"

# MIME type of Atom

[mediaTypes."application/atom+xml"]
suffixes = ["xml"]

# Custom Atom template of MemE

[outputFormats.SectionsAtom]
mediaType = "application/atom+xml"
baseName = "atom"

# Custom RSS template of MemE

[outputFormats.SectionsRSS]
mediaType = "application/rss+xml"
baseName = "rss"

# Search index for lunr.js

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "search"

# Search index for Algolia

[outputFormats.Algolia]
mediaType = "application/json"
baseName = "algolia"
isPlainText = true
notAlternative = true

# Hugo’s output control

[outputs]
page = ["HTML"]
home = ["HTML", "SectionsAtom", "SectionsRSS", "SearchIndex"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]

# Maximum number of items in the Atom & RSS feed

[services.rss]
limit = 20

##########################################

# Menu Settings

[menu]
## Menu bar
[[menu.main]]
url = "/"
name = "首页"
weight = 1
pre = "internal"
post = "home"
[[menu.main]]
url = "/posts/"
name = "文章"
weight = 2
pre = "internal"
post = "archive"
[[menu.main]]
url = "/categories/"
name = "分类"
weight = 3
pre = "internal"
post = "th"
[[menu.main]]
url = "/tags/"
name = "标签"
weight = 4
pre = "internal"
post = "tags"
[[menu.main]]
url = "/about/"
name = "关于"
weight = 5
pre = "internal"
post = "user-circle"
[[menu.main]]
weight = 6
identifier = "search"
post = "search"
[[menu.main]]
weight = 7
identifier = "lang-switcher"
[[menu.main]]
weight = 8
identifier = "theme-switcher"
post = "adjust"
##########################################

# Theme Settings

[params]
######################################
# Header

enableHeader = true

enableHeaderAutoHide = false

displayHeaderInHome = true

headerBackground = "linear-gradient(90deg, #f795331a 0, #f370551a 15%, #ef4e7b1a 30%, #a166ab1a 44%, #5073b81a 58%, #1098ad1a 72%, #07b39b1a 86%, #6dba821a 100%)"

headerLayout = "flex"
menuItemPadding = "0.5rem"

######################################
# Moved root-level settings here

googleAnalytics = 'G-HS7L12NVNJ'
newContentEditor = ""
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
titleCaseStyle = "none"
pluralizeListTitles = false
summaryLength = 42
enableEmoji = false
footnoteReturnLinkContents = "↩"
enableGitInfo = false
enableRobotsTXT = true
disablePathToLower = false
relativeURLs = false
uglyURLs = false


######################################
# Brand Bar (inside header)

siteBrandSVG = true

siteBrandSVGWidth = 180
siteBrandSVGHeight = 100
siteBrandSVGFill = "#fff"

siteBrandFontSize = 1
siteBrandFontColor = "var(--color-contrast-high)"


######################################
# Menu Bar

enableMenu = true

displayMenuInHome = true

activeInSection = false


######################################
# Homepage Layout

homeLayout = "posts"

homePoetry = []

homeLinksPadding = 1

homePoster = ""
homeVideoWebm = ""
homeVideoMp4 = ""
homeLogo = "/icons/mylogo.png"
homeLogoLink = ""
homeTitle = ""
homeMotto = ""
homeDescription = "何故的小站，记录生活、思考与写作。"
homeKeywords = ""
homeLinksDelimiter = ""

enableHideInHomepage = false


######################################
# Site Info

siteLogo = "/icons/mylogo.png"

favicon = "/favicon.ico" 

siteDescription = "何故的小站，记录生活、思考与写作"

siteCreatedTime = "2024-10-06T15:00:00+08:00"

siteTwitter = "1txcat"


######################################
# Category By

categoryBy = "categories"


######################################
# Categories Page

enableTree = true

displayPosts = true

displayPostsCount = true

limitPostsLimit = -1


######################################
# Tags Page

enableTagCloud = true

fontUnit = "em"
largestFontSize = 2.5
smallestFontSize = 1


######################################
# List Page

listWidth = 36

displayListTitle = true

listDateFormat = "January 2"

listDatePosition = "right"

groupByMonth = true

chineseZodiac = true

i18nYear = false
i18nMonth = false


######################################
# Taxonomy List Page

displayTaxonomyTermCount = true

limitEntriesLimit = -1


######################################
# Post Sections

# mainSections = ["posts"]


######################################
# Atom & RSS

includeContent = true

feedFooter = """> Read original: <{{ .Permalink }}>  
> Notice: This blog now offers email subscriptions—feel free to [subscribe via Substack](https://username.substack.com) to support my work!"""

######################################
# Dark Mode

enableDarkMode = true

defaultTheme = "dark"

hideThemeToggle = false
hideThemeToggleInHome = false

overrideSystemPreferences = false


######################################
# Web App

themeColor = "#fff"
themeColorDark = "#16171d"


######################################
# HTML Head Meta, SEO & Social Discovery

jsonLD = true
openGraph = true
twitterCards = true

autoDetectImages = true


######################################
# Service Worker

enableServiceWorker = false


######################################
# KaTeX (chemical equation supported)

enableKaTeX = false


######################################
# MathJax (chemical equation supported)

enableMathJax = false

disableMathJaxMenu = false


######################################
# Mermaid (https://github.com/mermaid-js/mermaid)

enableMermaid = false

mermaidTheme = 'default'
mermaidThemeDark = 'dark'


######################################
# Comments

enableComments = true

autoLoadComments = true

## Disqus
enableDisqus = false
disqusShortname = ""

## Valine
enableValine = false
valineAppId = ""
valineAppKey = ""
valinePlaceholder = "Just go go"
valinePath = ""
valineAvatar = "mm"
valineMeta = ["nick", "mail", "link"]
valinePageSize = 10
valineLang = "en"
valineVisitor = false
valineHighlight = true
valineAvatarForce = false
valineRecordIP = false
valineServerURLs = ""
valineEmojiCDN = ""
valineEmojiMaps = {}
valineEnableQQ = false
valineRequiredFields = []

## Utterances
enableUtterances = false
utterancesRepo = ""
utterancesIssueTerm = "pathname"
utterancesTheme = "github-light"
utterancesThemeDark = "photon-dark"
utterancesLabel = ""

## Gitalk
enableGitalk = false
gitalkClientID = "your_client_id"
gitalkClientSecret = "your_client_secret"
gitalkRepo = "your_repository"
gitalkOwner = "your_gitalk_owner"
gitalkAdmin = ["your_gitalk_admin"]
gitalkID = "pathname"
gitalkNumber = -1
gitalkLables = ["Gitalk"]
gitalkTitle = "default"
gitalkBody = "default"
gitalkLanguage = "en"
gitalkDistractionFreeMode = false
gitalkPerPage = 10
gitalkPagerDirection = "last"
gitalkCreateIssueManually = false
gitalkProxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token"
gitalkStaggerDelayBy = 150
gitalkAppearAnimation = "accordionVertical"
gitalkEnterAnimation = "accordionVertical"
gitalkLeaveAnimation = "accordionVertical"
gitalkEnableHotKey = true

## Giscus
enableGiscus = true
giscusRepo = "cnhegu/cnhegu.github.io"
giscusRepoId = "R_kgDOPOBCpg"
giscusCategory = "Announcements"
giscusCategoryId = "DIC_kwDOPOBCps4CtEv9"
giscusMapping = "title"
giscusStrict = 0
giscusReactionsEnabled = true
giscusEmitMetaData = false
giscusInputPosition = "bottom"
giscusTheme = "dark_dimmed"
giscusThemeDark = "dark_dimmed"
giscusLang = "zh-CN"

# Remark42
enableRemark42 = false
remark42Host = ""
remark42SiteId = "remark"
remark42Url = ""
remark42Components = ["embed"]
remark42MaxShownComments = 15
remark42MaxLastComments = 15
remark42Theme = "light"
remark42PageTitle = ""
remark42Locale = "en"
remark42ShowEmailSubscription = true
remark42ShowRssSubscription = true
remark42SimpleView = false
remark42NoFooter = false


######################################
# Google Analytics

enableGoogleAnalytics = true

trackingCodeType = "gtag"

trackingID = "G-HS7L12NVNJ"

googleAnalyticsPrivacy = true
noAttribution = true


######################################
# Google Site Verification

googleSiteVerification = "GCW3EwP2jAhK22WZTH5ZVTOCCZU4FtdrzKNTks-AzNw"


######################################
# Google AdSense

googleAdClient = ""

enableGoogleAutoAds = false

enableGoogleAdUnits = false
googleAdSlot = ""
googleAdSlotInArticle = ""
googleAdSlotAutoRelaxed = ""


######################################
# Yandex.Metrika

yandexMetrikaId = ""


######################################
# Post Settings

duration = 0.5

primaryColorLight = "220, 90%, 56%"
primaryColorDark = "200, 70%, 50%"

postWidth = 36

original = true


######################################
# Post Description

displayPostDescription = true


################3######################
# Post Meta Info

enablePostMeta = true

enablePostMetaInHome = true

postMetaDateFormat = "2006.1.2"

displayPublishedDate = true
publishedDateIcon = "calendar-alt"

displayModifiedDate = false
modifiedDateIcon = "calendar-check"

displayExpiredDate = true
expiredDateIcon = "calendar-times"

displayCategory = true
categoryIcon = "folder"
categoryDelimiter = "/"

displayWordCount = true
wordCountIcon = "pencil-alt"

displayReadingTime = true
readingTimeIcon = "clock"

displayBusuanziPagePV = false
busuanziPagePVIcon = "eye"


######################################
# Markdown Related

hrefTargetBlank = true


######################################
# Table of Contents

enableTOC = false

displayTOCTitle = true

displayTOCNum = true

linkHeadingsToTOC = true


######################################
# Headings Anchor

enableHeadingsAnchor = true

headingsOpt = "1-6"

anchorSymbol = "#"

anchorIcon = "link"

enableAnchorLink = true

enableAnchorAutoHide = false


######################################
# Caption

enableCaption = true

captionPrefix = "※ "


######################################
# Image Hosting

enableImageHost = false

imageHostURL = "https://example.com/"

headAlso = false


######################################
# Video Hosting

enableVideoHost = false

videoHostURL = "https://example.com/"


######################################
# Footnotes

squareBrackets = true

footnoteReturnLinkIcon = "angle-up"

insertHrBySelf = true


######################################
# Scrollbar
customizeScrollbar = true


######################################
# Typography

######################################
## Font Family

fontFamilySiteBrand = ""
fontFamilyMenu = ""
fontFamilyTitle = "'Comfortaa', sans-serif"
fontFamilyHeadings = "'Comfortaa', sans-serif"
fontFamilyCode = "'Source Code Pro', monospace"
fontFamilyQuote = ""
fontFamilyTOC = ""
fontFamilyCaption = ""
fontFamilyFooter = ""
fontFamilyBody = "'IBM Plex Serif', 'Inter', serif"

fontsLink = "https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:ital,wght@0,400;0,500;0,700;1,400;1,700&family=Inter:wght@400;500;700&family=Source+Code+Pro:ital,wght@0,400;0,700;1,400;1,700&family=Comfortaa:wght@700&display=swap"


######################################
## Font Size (unit: px)

fontSize = 18


######################################
## Tab Size

tabSize = 4


######################################
## Line Height

lineHeight = 1.618


######################################
## Paragraph Indents

enableParagraphIndent = true

indentFirstParagraph = false

paragraphStyle = "margin"


######################################
## Text Justification

enableJustify = false


######################################
## Drop Cap

enableDropCap = true

enableDropCapAfterHr = false

deleteHrBeforeDropCap = false


######################################
## Small Caps

enableSmallCaps = true


######################################
## Emphasis Point (Chinese)

enableEmphasisPoint = false


######################################
## Chinese Punctuation Glyph Correction

enableChinesePunctuationGlyphCorrection = false


######################################
# Post Copyright

enablePostCopyright = true

displayPostCopyright = true


######################################
# Post Updated Badge

enablePostUpdatedBadge = true

displayUpdatedBadge = true

enableBadgeTitle = true
badgeTitlePrefix = "Updated @ "


######################################
# Post Gitinfo

enablePostGitInfo = false

displayPostGitInfo = false

repoURL = ""
repoEditURL = ""
repoEditURLSuffix = ""

gitIcon = "code-branch"
displayCommitHash = true

displayCommitMessage = true
msgIcon = "info"

displayFeedback = true
feedbackIcon = "question"
feedbackText = "Feedback"

displayEditLink = true
editIcon = "edit"
editText = "Edit Me?"


######################################
# Post Share

enablePostShare = false

displayPostShare = true

displayShareOnText = false

postShareItems = ["facebook", "mastodon", "fediverse", "x", "linkedin", "telegram", "weibo", "douban", "qq", "qzone", "pocket", "hackernews", "qrcode", "email"]

fetchFediverseInstances = false


######################################
# Related Posts

enableRelatedPosts = true

displayRelatedPosts = true

relatedPostsNumber = 5

relatedPostsIcon = "plus-circle"


######################################
# Post Tags

enablePostTags = true

postTagsIcon = "tag"


######################################
# Previous/Next Post

enablePostNav = true

postNavInSection = true


######################################
# Minimal Footer

enableMinimalFooter = false
enableVerticalBarStructure = false

enableAboutPageMinimalFooter = false


######################################
# Back to Top

enableBackToTop = true

enableBackToTopAutoHide = true

displayBackToTopInHome = true

displayBackToTopOnMobile = false

backToTopIcon = "arrow-up"


######################################
# Footer

enableFooter = true

displayFooter = true

displayFooterInHome = true

displayCopyleftSymbol = false
displayCopyrightSymbol = true
displaySiteCreatedYear = false

iconBetweenYearAndAuthor = "heart"
iconColor = "#f06292"
iconAnimation = true

displaySiteAuthorName = true

displayPoweredBy = true

displaySiteCopyright = true
customFooter = ""

displayBusuanziSiteUVAndPV = true
busuanziSiteUVText = "访客数"
busuanziSiteUVIcon = "user"
busuanziSitePVText = "访问量"
busuanziSitePVIcon = "eye"

enableSocials = true


######################################
# Multilingual

enableLangToggle = false

hideLangToggleInHome = false

autoHideLangToggle = true


######################################
# Code Blocks

enableHighlight = true

enableOverflowY = true
maxHeight = 20

enableCopy = true
enableCopyAutoHide = true


######################################
# Fingerprinting and SRI

enableFingerprint = true

enableSRI = false


######################################
# Force HTTPS Redirection

enableForceHTTPS = false


######################################
# Smooth Scroll

enableSmoothScroll = true


######################################
# Medium Zoom

enableMediumZoom = true


######################################
# Instant Page

enableInstantPage = true


######################################
# Lunr search

enableLunrSearch = true


######################################
# Algolia search

enableAlgoliaSearch = false

algoliaAppId = ""
algoliaApiKey = ""
algoliaIndexName = ""


######################################
# 404 Page

fofPoster = ""

fofVideoWebm = ""
fofVideoMp4 = ""


######################################
# Customize host for third-party libraries

[params.lib]
host = "https://cdn.jsdelivr.net"
[params.lib.path]
clipboard = "/npm/clipboard-polyfill@2.8.6/dist/clipboard-polyfill.min.js"
instantsearch = "/npm/instantsearch.js@2/dist/instantsearch.min.js"
gitalk = "/npm/gitalk@1/dist/gitalk.min.js"
gitalk_css = "/npm/gitalk@1/dist/gitalk.css"
instantpage = "/npm/instant.page@5.1.0/instantpage.min.js"
katex = "/npm/katex@0.13.0/dist/katex.min.js"
katex_css = "/npm/katex@0.13.0/dist/katex.min.css"
katex_mhchem = "/npm/katex@0.13.0/dist/contrib/mhchem.min.js"
katex_auto_render = "/npm/katex@0.13.0/dist/contrib/auto-render.min.js"
lunr = "/npm/lunr@2.3.9/lunr.min.js"
lunr_tinyseg = "/npm/lunr-languages@1.4.0/tinyseg.js"
lunr_stemmer = "/npm/lunr-languages@1.4.0/min/lunr.stemmer.support.min.js"
lunr_lang = "/npm/lunr-languages@1.4.0/min/lunr.de.min.js"
mathjax = "/npm/mathjax@3.1.2/es5/tex-mml-chtml.js"
medium_zoom = "/npm/medium-zoom@latest/dist/medium-zoom.min.js"
mermaid = "/npm/mermaid@8.8.3/dist/mermaid.min.js"
qrcode = "/npm/qrcode-generator@1.4.4/qrcode.min.js"
valine = "/npm/valine@1.4.14/dist/Valine.min.js"
busuanzi = "https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"
utterances = "https://utteranc.es/client.js"


######################################
# Author’s information
[params.author]
name = "何故"
email = "comitist@gmail.com"
motto = "Viva La Vida"
avatar = "/icons/mylogo.png"
website = "https://www.hegu.me"
twitter = "1txcat"
fediverse = "@1txcat@mastodon.social"

# Force remote rebuild v2.0

[module]
 [[module.imports]]
    path = "github.com/cnhegu/hugo-theme-meme"
    disable = false