##########################################
# Site Settings

baseURL = "https://www.hegu.me/"
title = "何故小站"
languageCode = "zh-cn" # 建议将主语言代码改为中文
hasCJKLanguage = true
copyright = "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)"
googleAnalytics = 'G-4BMXNHL73E'
defaultContentLanguage = "zh-cn"
enableRobotsTXT = true

[frontmatter]
  lastmod = ["lastmod", ":git", ":fileModTime", ":default"]

[taxonomies]
  category = "categories"
  tag = "tags"

##########################################
# Menu Settings

[menu]
  [[menu.main]]
    pageref = "/"
    name = "首页"
    weight = 1
    post = "home"
  [[menu.main]]
    pageref = "/posts/"
    name = "文章"
    weight = 2
    post = "archive"
  [[menu.main]]
    pageref = "/categories/"
    name = "分类"
    weight = 3
    post = "th"
  [[menu.main]]
    pageref = "/tags/"
    name = "标签"
    weight = 4
    post = "tags"
  [[menu.main]]
    pageref = "/about/"
    name = "关于"
    weight = 5
    post = "user-circle"
  [[menu.main]]
    weight = 6
    identifier = "theme-switcher"
  [[menu.main]]
    weight = 8
    identifier = "search"
    post = "search"

##########################################
# Theme Settings (params)

[params]
  # --- 网站信息 ---
  siteLogo = "/icons/hegu-icon.png" # 用于 SEO 和社交分享
  siteDescription = "何故小站 - 记录，所见，所思，所想..."
  siteCreatedTime = "2025-07-17T15:00:00+08:00"
  siteTwitter = "gulogx" # 用于 Twitter Cards, 已更新

  # --- 首页布局 ---
  homeLayout = "posts"
  
  # --- 评论系统 ---
  enableComments = true
  [params.giscus]
    enableGiscus = true
    giscusRepo = "cnhegu/cnhegu.github.io"
    giscusRepoId = "R_kgDOPOBCpg"
    giscusCategory = "Announcements"
    giscusCategoryId = "DIC_kwDOPOBCps4CtEv9"
    giscusMapping = "title"
    giscusTheme = "dark_dimmed"
    giscusLang = "zh-CN"

  # --- 作者信息 (用于文章页等) ---
  [params.author]
    name = "何故"
    email = "comitist@gmail.com"
    motto = "Viva La Vida"
    avatar = "/icons/my-avatar.png"
    website = "https://www.hegu.me"
    twitter = "gulogx" # 作者的 Twitter ID, 已更新

  # --- 页脚社交链接 ---
  # 这个选项只负责开启或关闭页脚的社交链接区域
  # 具体链接内容由 data/Socials.toml 文件控制
  enableSocials = true

  # --- 其他主题功能 ---
  enableDarkMode = true
  defaultTheme = "dark"
  enableBackToTop = true
  enablePostCopyright = true
  enableRelatedPosts = true
  enablePostTags = true
  enablePostNav = true
  displayPoweredBy = true
  displayBusuanziSiteUVAndPV = true
  busuanziSiteUVText = "访客数"
  busuanziSitePVText = "访问量"
  enableLunrSearch = true
  enableMediumZoom = true
  enableInstantPage = true

# 以下为高级配置，保持默认即可
[outputs]
  home = ["HTML", "SectionsAtom", "SectionsRSS", "SearchIndex"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
[services.rss]
  limit = -1
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
```

### **最后一步**

1.  请完成上面**两个步骤**：创建/修改 `data/Socials.toml` 文件，并用新代码替换 `hugo.toml` 文件。
2.  在命令行运行 `hugo server`，在本地预览一下页脚的社交链接是否已经正确更新。
3.  确认无误后，将您的修改推送到 GitHub。

这次我们根据主题的正确用法，修改了专门的 `data/Socials.toml` 文件，问题一定能得到